### ISSUE TITLE
Include upstream MIT license

### ISSUE THREAD

**Issue by auscompgeek** [Eaglestrike/navx-rs#4]
It would also be a good idea to license this under MIT as well, to avoid complicating the copyright/licensing. (That would depend on https://github.com/Lytigas/first-rust-competition/issues/16.)

**Comment by bookofportals** [comment]
We can't do that until first-rust-competition does. As soon as they do, if they do, we can relicense this.

**Comment by auscompgeek** [comment]
Good point. In the meantime, you'll have to provide a copy of upstream's license anyway, otherwise you'd be in violation of the license as a derivative work.

**Comment by Lytigas** [comment]
@auscompgeek Do you mean the upstream navx library's license? I'm not sure whether or not this would count as a derivative work, except maybe for the protocol constants.

**Comment by bookofportals** [comment]
This has been resolved.
