### ISSUE TITLE
Move to first-rust-competition org?

### ISSUE THREAD

**Issue by auscompgeek** [Eaglestrike/navx-rs#8]
Hey team,

We're trying to consolidate efforts over at @first-rust-competition. Please consider this as an invitation to join us in hopefully consolidating the currently fragmented Rust in FRC community.

**Comment by jmeggitt** [comment]
I think it is @Lytigas's choice to move this repo or not.

**Comment by auscompgeek** [comment]
Heh, funnily enough I'm still waiting for him to move the first-rust-competition monorepo too.

**Comment by Lytigas** [comment]
Doing it right now!
